# Generated by Django 2.2 on 2018-07-17 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_tutorial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('lecturer', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.FileField(null=True, upload_to='lectures/')),
                ('resources', models.FileField(default='null', upload_to='resources/')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('registered_students', models.ManyToManyField(through='tutorials.Registered_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='registered_students',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='tutorials.Tutorial'),
        ),
    ]
