# Generated by Django 2.2 on 2018-07-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_cove_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='cove_imgae',
            new_name='cove_image',
        ),
    ]
