# Generated by Django 2.2 on 2018-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20180722_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='prize',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
