# Generated by Django 2.2 on 2018-07-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20180722_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/'),
        ),
    ]
