# Generated by Django 2.2 on 2018-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_auto_20180722_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='cove_image',
            new_name='cover_image',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='resources',
            field=models.FileField(blank=True, default='null', null=True, upload_to='resources/'),
        ),
    ]
