# Generated by Django 2.2 on 2018-08-09 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_auto_20180723_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to=settings.AUTH_USER_MODEL),
        ),
    ]
