# Generated by Django 2.2 on 2018-08-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_auto_20180823_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prize',
        ),
    ]
