# Generated by Django 2.2 on 2018-08-23 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0012_remove_course_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registered_students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
