# Generated by Django 2.2 on 2018-08-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_tutorial_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prize',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
