# Generated by Django 2.2 on 2018-08-23 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0019_auto_20180823_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_student',
            name='student',
        ),
        migrations.AddField(
            model_name='registered_student',
            name='student',
            field=models.ManyToManyField(related_name='enrolled_tutorial', to=settings.AUTH_USER_MODEL),
        ),
    ]
