# Generated by Django 2.2 on 2018-08-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0021_auto_20180824_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_student',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='tutorials.Course'),
        ),
        migrations.AlterField(
            model_name='registered_student',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_tutorial', to=settings.AUTH_USER_MODEL),
        ),
    ]
