# Generated by Django 2.2 on 2018-08-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0022_auto_20180824_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='tutorials.Course'),
        ),
    ]
