# Generated by Django 2.2 on 2018-08-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Free', 'free'), ('Professional', 'pro'), ('Enterprise', 'ent')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
        migrations.AddField(
            model_name='profile',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.Membership'),
        ),
    ]
