# Generated by Django 2.2 on 2018-08-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180822_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('pro', 'Professional'), ('ent', 'Enterprise')], max_length=50),
        ),
    ]
